#!/usr/bin/env bash

# System wide functions and aliases
# Environment stuff goes in /etc/profile

# It's NOT a good idea to change this file unless you know what you
# are doing. It's much better to create a custom.sh shell script in
# /etc/profile.d/ to make custom changes to your environment, as this
# will prevent the need for merging in future updates.

# Prevent doublesourcing
if [ -z "$BASHRCSOURCED" ]; then
  BASHRCSOURCED="Y"

  # are we an interactive shell?
  if [ -n "$PS1" ]; then
    # Turn on parallel history
    shopt -s histappend
    history -a
    PROMPT_COMMAND="$PROMPT_COMMAND "
    # Turn on checkwinsize
    shopt -s checkwinsize
  fi

  if ! shopt -q login_shell; then # We're not a login shell
    # Need to redefine pathmunge, it gets undefined at the end of /etc/profile
    pathmunge() {
      case ":${PATH}:" in
      *:"$1":*) ;;
      *)
        if [ "$2" = "after" ]; then
          PATH=$PATH:$1
        else
          PATH=$1:$PATH
        fi
        ;;
      esac
    }

    # By default, we want umask to get set. This sets it for non-login shell.
    # Current threshold for system reserved uid/gids is 200
    # You could check uidgid reservation validity in
    # /usr/share/doc/setup-*/uidgid file
    if [ $UID -gt 199 ] && [ "$(/usr/bin/id -gn)" = "$(/usr/bin/id -un)" ]; then
      umask 002
    else
      umask 022
    fi

    SHELL=/bin/bash
    # Only display echos from profile.d scripts if we are no login shell
    # and interactive - otherwise just process them to set envvars
    for i in /etc/profile.d/*.sh; do
      if [ -r "$i" ]; then
        if [ "$PS1" ]; then
          . "$i"
        else
          . "$i" >/dev/null
        fi
      fi
    done

    unset i
    unset -f pathmunge
  fi
fi
# vim:ts=4:sw=4
